# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paul Cleary
email: pcleary00@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer digging Scala and all the things
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pcleary01
github_username:  pcleary00

# Build settings
markdown: kramdown
